---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
```{r}
#loading the necessary libraries 
library(arules)
library(arulesViz)
```

```{r}
# read the csv file that contains the transactions 
transactions <- read.transactions("C:/Users/Amjad/Desktop/R_work/Assignment 2/transactions.csv",rm.duplicates=TRUE,sep=",")

class(transactions)
```
```{r}
# plot the frequency of items
itemFrequencyPlot(transactions, topN = 5)
```
```{r}
library(arules)
# build the model 
```

# with max length = 3 

```{r}
# set better support and confidence levels to learn more rules
rules <- apriori(transactions, parameter = list(support=0.002, confidence =0.20, maxlen=3))

```


```{r}
#summarize the results 
summary(rules)
```


```{r}
# look at the first three rules
inspect(rules[1:3])
```


```{r}
# sorting  rules by lift to determine the rule with the highest lift 
greatest_lift_rule <- sort(rules, by="lift")[1]
inspect(greatest_lift_rule)
```

# with max length = 2 

```{r}
# change the maxlen to 2 
updated_rules <- apriori(transactions, parameter = list(support=0.002, confidence =0.20, maxlen=2))
updated_rules
```


```{r}
#summarize the results 
summary(updated_rules)
```


```{r}
# look at the first three rules
inspect(updated_rules[1:3])
```


```{r}
# sorting  rules by lift to determine the rule with the highest lift 
highest_lift_rule <- sort(updated_rules, by="lift")[1]
inspect(highest_lift_rule)
```


```{r}
# compare between greatest_lift_rule with maxlen = 3 vs highest_lift_rule with maxlen = 2
print("with max length = 3")
print(inspect(greatest_lift_rule))
```
```{r}
print("with max length = 2")
print(inspect(highest_lift_rule))
```
















